const fs=require('node:fs');
const path=require('node:path');
const escape=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function writeReview(directory,report){
 const scriptData=JSON.stringify(report).replaceAll('<','\\u003c').replaceAll('>','\\u003e').replaceAll('&','\\u0026');
 const core=fs.readFileSync(path.join(__dirname,'../extension/core.js'),'utf8');
 const css=fs.readFileSync(path.join(__dirname,'../extension/ui.css'),'utf8');
 const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Patchmason · ${escape(report.environment.platform)} capture</title><style>${css}.mobile-fields{margin-bottom:24px}.media{max-width:100%;max-height:480px;display:block;margin:15px auto}.check-row{display:flex;gap:10px;align-items:flex-start;padding:15px 0;border-bottom:1px solid var(--line)}.check-row input{margin-top:5px;accent-color:var(--accent)}.check-row pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.6 ui-monospace,monospace;margin:0}.review-layout{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:24px}.actions{display:grid;gap:9px}.actions button{width:100%}@media(max-width:850px){.review-layout{grid-template-columns:1fr}}</style>
<header class="topbar"><div class="brand"><img src="icons/patchmason-mark.svg" alt="" width="32" height="32">patchmason</div><span class="pill">${escape(report.source.toUpperCase())} · LOCAL CAPTURE</span></header><main class="workspace"><div class="heading"><div><div class="eyebrow">CAPTURE / REVIEW / HAND OFF</div><h1>The bug, with context.</h1><p class="muted">${escape(report.environment.device)} · ${escape(report.environment.app)}</p></div></div>
<div class="review-layout"><div class="stack"><section class="panel"><div class="panel-head"><h2>What went wrong?</h2></div><div class="panel-body fields"><label for="title">Report title</label><input id="title" maxlength="160"><label for="expected">Expected behavior</label><textarea id="expected" maxlength="4000" placeholder="What should have happened?"></textarea><label for="actual">Actual behavior</label><textarea id="actual" maxlength="4000" placeholder="What happened instead?"></textarea></div></section><section class="panel"><div class="panel-head"><h2>App logs & annotated steps</h2><span class="eyebrow" id="count"></span></div><div class="panel-body"><p class="notice">Uncheck any private or irrelevant lines to exclude them from your export.</p><div id="events"></div></div></section><section class="panel"><div class="panel-head"><h2>Screenshots & video</h2></div><div class="panel-body" id="media"></div></section></div>
<aside class="stack"><section class="export-card"><div class="eyebrow">THE HANDOFF</div><h2>Ready for your<br>coding agent.</h2><p>Describe the bug, select the evidence, then export your reviewed report.</p><label class="review-check"><input type="checkbox" id="reviewed"><span>I reviewed all selected text, screenshots, and video for private information.</span></label><button class="primary" id="copy" disabled>Copy for coding agent</button><button class="secondary" id="md" disabled>Download Markdown</button><button class="secondary" id="json" disabled>Download JSON</button><p id="status" role="status"></p></section><section class="panel"><div class="panel-body notice"><strong>Before you share</strong><p>Selected media are referenced by filename. Attach those files separately. JSON and Markdown do not embed the video or screenshots.</p><p>Unchecking evidence only excludes it from this export. The original draft, this review file, and media remain in the capture directory. Do not share the whole directory without checking it.</p><p>Review selections and edits live in this page until you download; they are not saved back to disk.</p><strong>Capture limits</strong><p>${escape(report.limitations)}</p><p>${escape(report.stopReason||'Recording in progress. Reopen this file after stopping.')}</p></div></section></aside></div></main>
<script>${core}</script><script>
const report=${scriptData};const $=id=>document.getElementById(id);
const selected=new Set(report.events.map(e=>e.id));const media=new Set(report.artifacts.map(a=>a.name));
$('title').value=report.title;$('expected').value=report.expected;$('actual').value=report.actual;
function gate(){for(const id of ['copy','md','json'])$(id).disabled=!$('reviewed').checked||!report.endedAt;}
function invalidate(){$('reviewed').checked=false;gate();}
for(const id of ['title','expected','actual'])$(id).addEventListener('input',invalidate);
$('reviewed').onchange=gate;$('count').textContent=report.events.length+' EVENTS';
for(const e of report.events){const row=document.createElement('label');row.className='check-row';const box=document.createElement('input');box.type='checkbox';box.checked=true;box.setAttribute('aria-label','Include event '+e.id);box.onchange=()=>{box.checked?selected.add(e.id):selected.delete(e.id);invalidate();};const text=document.createElement('pre');text.textContent='+'+(e.ms/1000).toFixed(1)+'s · '+e.kind+'\\n'+e.message;row.append(box,text);$('events').append(row);}
if(!report.events.length)$('events').textContent='No app log lines or notes were captured.';
for(const artifact of report.artifacts){if(!/^(screenshot-\\d+\\.png|recording\\.(mp4|webm))$/.test(artifact.name))continue;const row=document.createElement('div');const label=document.createElement('label');label.className='check-row';const box=document.createElement('input');box.type='checkbox';box.checked=true;box.onchange=()=>{box.checked?media.add(artifact.name):media.delete(artifact.name);invalidate();};label.append(box,document.createTextNode('Include '+artifact.name));const preview=document.createElement(artifact.kind==='video'?'video':'img');preview.className='media';preview.src=artifact.name;if(artifact.kind==='video'){preview.controls=true;preview.preload='metadata';}else preview.alt='Simulator screenshot — review for sensitive pixels';row.append(label,preview);$('media').append(row);}
if(!report.artifacts.length)$('media').textContent='No media captured. Use s for a screenshot, or --video when starting a recording.';
function output(){return {...report,title:PatchmasonCore.redact($('title').value,160),expected:PatchmasonCore.redact($('expected').value,4000),actual:PatchmasonCore.redact($('actual').value,4000),events:report.events.filter(e=>selected.has(e.id)),artifacts:report.artifacts.filter(a=>media.has(a.name))};}
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
$('md').onclick=()=>{if($('reviewed').checked)download(PatchmasonCore.markdown(output()),'Patchmason-reviewed.md','text/markdown');};
$('json').onclick=()=>{if($('reviewed').checked)download(JSON.stringify(PatchmasonCore.portable(output()),null,2),'Patchmason-reviewed.json','application/json');};
$('copy').onclick=async()=>{if(!$('reviewed').checked)return;try{await navigator.clipboard.writeText(PatchmasonCore.markdown(output()));$('status').textContent='Copied. Paste into your coding agent.';}catch{$('status').textContent='Clipboard unavailable in this browser. Download Markdown instead.';}};gate();
</script></html>`;
 fs.writeFileSync(path.join(directory,'review.html'),html,{mode:0o600});
}
module.exports={writeReview};
