const $=id=>document.getElementById(id);const token=document.querySelector('meta[name="bugdrop-token"]').content;let busy=false,state={},generation=0,devices=new Map(),desktopVideoAvailable=false,videoRecorder=null,videoChunks=[],videoFinalizing=false,targetReady=false,targetGeneration=0;
async function api(route,body){const res=await fetch('/api/'+route,{method:body?'POST':'GET',headers:{'X-BugDrop-Token':token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Request failed');return data;}
async function safe(fn){$('error').hidden=true;try{await fn();}catch(e){$('error').textContent=e.message;$('error').hidden=false;}}
function options(id,items,empty){$(id).replaceChildren();const first=document.createElement('option');first.value='';first.textContent=empty;$(id).append(first);for(const item of items){const option=document.createElement('option');option.value=item.id;option.textContent=item.name;$(id).append(option);}}
function update(){const running=!!state.recording,locked=running||state.starting||state.pending||busy||videoFinalizing||(!!videoRecorder&&!running),desktop=devices.get($('device').value)?.platform==='desktop';$('start').disabled=locked||!$('app').value||!targetReady;$('start').hidden=running;$('stop').hidden=!running;for(const id of ['device','app','refresh'])$(id).disabled=locked;$('video').disabled=locked||(desktop&&!desktopVideoAvailable);if(desktop&&!desktopVideoAvailable)$('video').checked=false;$('video-help').textContent=desktop?desktopVideoAvailable?'Video records only the selected app window. Screenshots also capture that window even when BugDrop is in front. Review media before sharing.':'Desktop video requires the BugDrop desktop app. Screenshots remain available.':'Video records all visible pixels. Screenshots are taken only when you click the screenshot button. Review media before sharing.';for(const id of ['shot','note','add-note'])$(id).disabled=!running;$('badge').textContent=running?'● Recording':videoFinalizing?'Saving video…':state.starting?'Starting…':state.report?.endedAt?'Report ready':'Ready';$('badge').classList.toggle('recording',running);$('output').textContent=state.output||'Your capture status will appear here.';$('count').textContent=state.report?state.report.events.length+' EVENTS SAVED':'NO CAPTURE YET';$('review').hidden=!state.review||videoFinalizing;if(state.review)$('review').href=state.review;$('location').textContent=state.dir||'';}
async function refresh(){const n=++generation;++targetGeneration;targetReady=false;busy=true;update();try{const data=await api('devices');if(n!==generation)return;desktopVideoAvailable=data.desktopVideoAvailable===true;devices=new Map(data.devices.map(device=>[device.id,device]));options('device',data.devices.map(d=>({...d,name:d.name+' · '+(d.platform==='desktop'?'DESKTOP':d.platform.toUpperCase())})),data.devices.length?'Choose a computer or device':'No capture targets found');options('app',[],'Choose a target first');$('warnings').textContent=data.warnings.join(' ');}finally{busy=false;update();}}
$('refresh').onclick=()=>safe(refresh);
$('device').onchange=()=>safe(async()=>{const n=++generation;++targetGeneration;targetReady=false;options('app',[],'Loading apps…');busy=true;update();try{if(!$('device').value)return;const apps=await api('apps?device='+encodeURIComponent($('device').value));if(n===generation)options('app',apps,apps.length?(devices.get($('device').value)?.platform==='desktop'?'Choose a running app':'Choose your app'):'No eligible apps found');}finally{busy=false;update();}});
$('app').onchange=()=>safe(async()=>{const n=++targetGeneration;targetReady=false;update();if(!$('app').value)return;await api('target',{device:$('device').value,app:$('app').value});if(n===targetGeneration){targetReady=true;update();}});
$('start').onclick=()=>safe(async()=>{busy=true;update();const desktopVideo=$('video').checked&&devices.get($('device').value)?.platform==='desktop';try{if(desktopVideo){const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});try{videoChunks=[];videoRecorder=new MediaRecorder(stream,{mimeType:'video/webm',videoBitsPerSecond:1500000});videoRecorder.ondataavailable=event=>{if(event.data.size)videoChunks.push(event.data);};videoRecorder.start(1000);stream.getVideoTracks()[0]?.addEventListener('ended',()=>{if(state.recording)$('stop').click();},{once:true});}catch(error){stream.getTracks().forEach(track=>track.stop());throw error;}}await api('start',{device:$('device').value,app:$('app').value,video:$('video').checked});state=await api('state');}catch(error){if(videoRecorder){videoRecorder.stream.getTracks().forEach(track=>track.stop());videoRecorder=null;videoChunks=[];}throw error;}finally{busy=false;update();}});
$('stop').onclick=()=>safe(async()=>{await api('stop',{});$('stop').disabled=true;});
$('shot').onclick=()=>safe(async()=>{await api('screenshot',{});});
$('add-note').onclick=()=>safe(async()=>{if(!$('note').value.trim())return;await api('note',{text:$('note').value});$('note').value='';});
async function finalizeVideo(){if(!videoRecorder||videoFinalizing)return;videoFinalizing=true;update();try{const recorder=videoRecorder;const blob=await new Promise((resolve,reject)=>{recorder.addEventListener('stop',()=>resolve(new Blob(videoChunks,{type:'video/webm'})),{once:true});recorder.addEventListener('error',event=>reject(event.error||new Error('Video recording failed.')),{once:true});recorder.stop();});recorder.stream.getTracks().forEach(track=>track.stop());videoRecorder=null;videoChunks=[];if(blob.size<32)throw new Error('No desktop video was captured.');for(let attempt=0;attempt<20;attempt++){state=await api('state');if(state.report?.endedAt&&!state.recording)break;await new Promise(resolve=>setTimeout(resolve,500));}if(!state.report?.endedAt)throw new Error('The report did not finish before video upload.');const response=await fetch('/api/video',{method:'POST',headers:{'X-BugDrop-Token':token,'Content-Type':'video/webm'},body:blob});const result=await response.json();if(!response.ok)throw new Error(result.error||'Video could not be saved.');state=await api('state');}finally{videoFinalizing=false;update();}}
safe(refresh);setInterval(async()=>{try{state=await api('state');if(!state.recording)$('stop').disabled=false;if(videoRecorder&&!state.recording&&!state.starting){if(state.report?.endedAt)await finalizeVideo();else if(state.exitCode!==undefined){videoRecorder.stream.getTracks().forEach(track=>track.stop());videoRecorder=null;videoChunks=[];throw new Error('The capture ended before the desktop video could be saved.');}}update();}catch(e){$('error').textContent=e.message;$('error').hidden=false;}},1500);
async function loadReports(){
 $('reports-error').hidden=true;
 try{
  const {reports}=await api('reports');const list=$('reports-list');list.replaceChildren();
  if(!reports.length){const empty=document.createElement('p');empty.className='notice';empty.textContent='No completed bug reports yet. Record a bug to see it here.';list.append(empty);return;}
  for(const report of reports){
   const card=document.createElement('article');card.className='report-card';
   const info=document.createElement('div');const title=document.createElement('h2');title.textContent=report.title;
   const meta=document.createElement('p');meta.className='muted';meta.textContent=[report.app||report.source,new Date(report.startedAt).toLocaleString(),report.events+' events'].join(' · ');
   info.append(title,meta);
   const actions=document.createElement('div');actions.className='report-actions';
   const solved=document.createElement('label');solved.className='solved-label';const check=document.createElement('input');check.type='checkbox';check.checked=report.solved;const label=document.createElement('span');label.textContent='Solved';solved.append(check,label);
   check.onchange=async()=>{check.disabled=true;try{await api('report-status',{id:report.id,solved:check.checked});card.classList.toggle('solved',check.checked);}catch(e){check.checked=!check.checked;$('reports-error').textContent=e.message;$('reports-error').hidden=false;}finally{check.disabled=false;}};
   const open=document.createElement('a');open.className='review-link';open.href=report.review;open.textContent='Open bug report →';
   actions.append(solved,open);card.append(info,actions);card.classList.toggle('solved',report.solved);list.append(card);
  }
 }catch(e){$('reports-error').textContent=e.message;$('reports-error').hidden=false;}
}
$('reload-reports').onclick=loadReports;
function showScreen(path){
 const showingReports=path==='/reports';$('record-screen').hidden=showingReports;$('reports-screen').hidden=!showingReports;
 $('nav-record').removeAttribute('aria-current');$('nav-reports').removeAttribute('aria-current');
 $(showingReports?'nav-reports':'nav-record').setAttribute('aria-current','page');
 if(showingReports)loadReports();
}
for(const [id,path] of [['nav-record','/'],['nav-reports','/reports']])$(id).onclick=event=>{event.preventDefault();history.pushState({},'',path);showScreen(path);};
window.onpopstate=()=>showScreen(location.pathname);
showScreen(location.pathname);
